symbols: [],
user_mentions: [Array],
urls: [Array] },
source: '<a href="http://sproutsocial.com" rel="nofollow">Sprout Social</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
{ id: 91985735,
id_str: '91985735',
name: 'Node.js',
screen_name: 'nodejs',
location: 'Earth',
description: 'The Node.js JavaScript Runtime',
url: 'https://t.co/X32n3a0B1h',
entities: [Object],
protected: false,
followers_count: 515428,
friends_count: 718,
listed_count: 6714,
created_at: 'Mon Nov 23 10:57:50 +0000 2009',
favourites_count: 1569,
utc_offset: -25200,
time_zone: 'Pacific Time (US & Canada)',
geo_enabled: true,
verified: true,
statuses_count: 5384,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_banner_url: 'https://pbs.twimg.com/profile_banners/91985735/1513020552',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 149,
favorite_count: 179,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' },
{ created_at: 'Fri Apr 27 20:30:06 +0000 2018',
id: 989964930681012200,
id_str: '989964930681012225',
text: 'ICYMI: Changes are coming for a few #nodejs release lines. These changes are covered in this blog post: https://t.co/tR8Igc1Ism',
truncated: false,
entities:
{ hashtags: [Array],
symbols: [],
user_mentions: [],
urls: [Array] },
source: '<a href="http://sproutsocial.com" rel="nofollow">Sprout Social</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
{ id: 91985735,
id_str: '91985735',
name: 'Node.js',
screen_name: 'nodejs',
location: 'Earth',
description: 'The Node.js JavaScript Runtime',
url: 'https://t.co/X32n3a0B1h',
entities: [Object],
protected: false,
followers_count: 515428,
friends_count: 718,
listed_count: 6714,
created_at: 'Mon Nov 23 10:57:50 +0000 2009',
favourites_count: 1569,
utc_offset: -25200,
time_zone: 'Pacific Time (US & Canada)',
geo_enabled: true,
verified: true,
statuses_count: 5384,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_banner_url: 'https://pbs.twimg.com/profile_banners/91985735/1513020552',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 29,
favorite_count: 37,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' },
{ created_at: 'Fri Apr 27 20:25:04 +0000 2018',
id: 989963663338598400,
id_str: '989963663338598400',
text: '@rajatkumar All meetings are posted on YouTube, if you want to get that details, you can head here… https://t.co/prWyUjUO81',
truncated: true,
entities:
{ hashtags: [],
symbols: [],
user_mentions: [Array],
urls: [Array] },
source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
in_reply_to_status_id: 989928711188168700,
in_reply_to_status_id_str: '989928711188168705',
in_reply_to_user_id: 14237178,
in_reply_to_user_id_str: '14237178',
in_reply_to_screen_name: 'rajatkumar',
user:
{ id: 91985735,
id_str: '91985735',
name: 'Node.js',
screen_name: 'nodejs',
location: 'Earth',
description: 'The Node.js JavaScript Runtime',
url: 'https://t.co/X32n3a0B1h',
entities: [Object],
protected: false,
followers_count: 515428,
friends_count: 718,
listed_count: 6714,
created_at: 'Mon Nov 23 10:57:50 +0000 2009',
favourites_count: 1569,
utc_offset: -25200,
time_zone: 'Pacific Time (US & Canada)',
geo_enabled: true,
verified: true,
statuses_count: 5384,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_banner_url: 'https://pbs.twimg.com/profile_banners/91985735/1513020552',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 1,
favorite_count: 1,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' },
{ created_at: 'Fri Apr 27 16:54:09 +0000 2018',
id: 989910582194126800,
id_str: '989910582194126849',
text: '@crapougnax @linuxfoundation TGIF. The correct survey is here https://t.co/xb5BhwidV7 and closes May 4. Sorry about that!',
truncated: false,
entities:
{ hashtags: [],
symbols: [],
user_mentions: [Array],
urls: [Array] },
source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
in_reply_to_status_id: 989903877624516600,
in_reply_to_status_id_str: '989903877624516609',
in_reply_to_user_id: 14918655,
in_reply_to_user_id_str: '14918655',
in_reply_to_screen_name: 'crapougnax',
user:
{ id: 91985735,
id_str: '91985735',
name: 'Node.js',
screen_name: 'nodejs',
location: 'Earth',
description: 'The Node.js JavaScript Runtime',
url: 'https://t.co/X32n3a0B1h',
entities: [Object],
protected: false,
followers_count: 515428,
friends_count: 718,
listed_count: 6714,
created_at: 'Mon Nov 23 10:57:50 +0000 2009',
favourites_count: 1569,
utc_offset: -25200,
time_zone: 'Pacific Time (US & Canada)',
geo_enabled: true,
verified: true,
statuses_count: 5384,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_banner_url: 'https://pbs.twimg.com/profile_banners/91985735/1513020552',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 2,
favorite_count: 0,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' },
{ created_at: 'Fri Apr 27 16:53:42 +0000 2018',
id: 989910472186105900,
id_str: '989910472186105863',
text: 'It appears we have linked to the wrong survey. The correct survey is here https://t.co/xb5Bhw0D3z and closes May 4. Sorry about that!',
truncated: false,
entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Array] },
source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
in_reply_to_status_id: 989897461031370800,
in_reply_to_status_id_str: '989897461031370752',
in_reply_to_user_id: 91985735,
in_reply_to_user_id_str: '91985735',
in_reply_to_screen_name: 'nodejs',
user:
{ id: 91985735,
id_str: '91985735',
name: 'Node.js',
screen_name: 'nodejs',
location: 'Earth',
description: 'The Node.js JavaScript Runtime',
url: 'https://t.co/X32n3a0B1h',
entities: [Object],
protected: false,
followers_count: 515428,
friends_count: 718,
listed_count: 6714,
created_at: 'Mon Nov 23 10:57:50 +0000 2009',
favourites_count: 1569,
utc_offset: -25200,
time_zone: 'Pacific Time (US & Canada)',
geo_enabled: true,
verified: true,
statuses_count: 5384,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_banner_url: 'https://pbs.twimg.com/profile_banners/91985735/1513020552',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 5,
favorite_count: 11,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' },
{ created_at: 'Fri Apr 27 16:02:00 +0000 2018',
id: 989897461031370800,
id_str: '989897461031370752',
text: 'The @linuxfoundation is looking for open source professionals &amp; hiring managers to give input on the job market. If… https://t.co/0l2bOJXNOf',
truncated: true,
entities:
{ hashtags: [],
symbols: [],
user_mentions: [Array],
urls: [Array] },
source: '<a href="http://sproutsocial.com" rel="nofollow">Sprout Social</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
{ id: 91985735,
id_str: '91985735',
name: 'Node.js',
screen_name: 'nodejs',
location: 'Earth',
description: 'The Node.js JavaScript Runtime',
url: 'https://t.co/X32n3a0B1h',
entities: [Object],
protected: false,
followers_count: 515428,
friends_count: 718,
listed_count: 6714,
created_at: 'Mon Nov 23 10:57:50 +0000 2009',
favourites_count: 1569,
utc_offset: -25200,
time_zone: 'Pacific Time (US & Canada)',
geo_enabled: true,
verified: true,
statuses_count: 5384,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_banner_url: 'https://pbs.twimg.com/profile_banners/91985735/1513020552',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 14,
favorite_count: 33,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' },
{ created_at: 'Fri Apr 27 15:40:18 +0000 2018',
id: 989891998277566500,
id_str: '989891998277566465',
text: 'RT @evanhlucas: Thanks node 10. I’ll happily take an additional 10k req/s! https://t.co/EN2nxfwslu',
truncated: false,
entities:
{ hashtags: [],
symbols: [],
user_mentions: [Array],
urls: [],
media: [Array] },
extended_entities: { media: [Array] },
source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
{ id: 91985735,
id_str: '91985735',
name: 'Node.js',
screen_name: 'nodejs',
location: 'Earth',
description: 'The Node.js JavaScript Runtime',
url: 'https://t.co/X32n3a0B1h',
entities: [Object],
protected: false,
followers_count: 515428,
friends_count: 718,
listed_count: 6714,
created_at: 'Mon Nov 23 10:57:50 +0000 2009',
favourites_count: 1569,
utc_offset: -25200,
time_zone: 'Pacific Time (US & Canada)',
geo_enabled: true,
verified: true,
statuses_count: 5384,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_banner_url: 'https://pbs.twimg.com/profile_banners/91985735/1513020552',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
retweeted_status:
{ created_at: 'Thu Apr 26 23:12:02 +0000 2018',
id: 989643291368083500,
id_str: '989643291368083456',
text: 'Thanks node 10. I’ll happily take an additional 10k req/s! https://t.co/EN2nxfwslu',
truncated: false,
entities: [Object],
extended_entities: [Object],
source: '<a href="http://tapbots.com/software/tweetbot/mac" rel="nofollow">Tweetbot for Mac</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user: [Object],
geo: null,
coordinates: null,
place: [Object],
contributors: null,
is_quote_status: false,
retweet_count: 110,
favorite_count: 444,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' },
is_quote_status: false,
retweet_count: 110,
favorite_count: 0,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' },
{ created_at: 'Fri Apr 27 14:10:00 +0000 2018',
id: 989869276030029800,
id_str: '989869276030029824',
text: 'Are you a large enterprise using #nodejs in production?  Please participate in the upcoming Node.js community enter… https://t.co/Neu3Sr2F0v',
truncated: true,
entities:
{ hashtags: [Array],
symbols: [],
user_mentions: [],
urls: [Array] },
source: '<a href="http://sproutsocial.com" rel="nofollow">Sprout Social</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
{ id: 91985735,
id_str: '91985735',
name: 'Node.js',
screen_name: 'nodejs',
location: 'Earth',
description: 'The Node.js JavaScript Runtime',
url: 'https://t.co/X32n3a0B1h',
entities: [Object],
protected: false,
followers_count: 515428,
friends_count: 718,
listed_count: 6714,
created_at: 'Mon Nov 23 10:57:50 +0000 2009',
favourites_count: 1569,
utc_offset: -25200,
time_zone: 'Pacific Time (US & Canada)',
geo_enabled: true,
verified: true,
statuses_count: 5384,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_banner_url: 'https://pbs.twimg.com/profile_banners/91985735/1513020552',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 30,
favorite_count: 45,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' },
{ created_at: 'Fri Apr 27 13:13:02 +0000 2018',
id: 989854936992231400,
id_str: '989854936992231425',
text: 'What\'s the future of #nodejs and the #nodejsfoundation? @mrhinkle provides his thoughts in this Q&amp;A with… https://t.co/SXLI6rzPlz',
truncated: true,
entities:
{ hashtags: [Array],
symbols: [],
user_mentions: [Array],
urls: [Array] },
source: '<a href="http://sproutsocial.com" rel="nofollow">Sprout Social</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
{ id: 91985735,
id_str: '91985735',
name: 'Node.js',
screen_name: 'nodejs',
location: 'Earth',
description: 'The Node.js JavaScript Runtime',
url: 'https://t.co/X32n3a0B1h',
entities: [Object],
protected: false,
followers_count: 515428,
friends_count: 718,
listed_count: 6714,
created_at: 'Mon Nov 23 10:57:50 +0000 2009',
favourites_count: 1569,
utc_offset: -25200,
time_zone: 'Pacific Time (US & Canada)',
geo_enabled: true,
verified: true,
statuses_count: 5384,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_banner_url: 'https://pbs.twimg.com/profile_banners/91985735/1513020552',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 19,
favorite_count: 31,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' },
{ created_at: 'Thu Apr 26 23:15:10 +0000 2018',
id: 989644083143553000,
id_str: '989644083143553025',
text: '✨ @captainsafia has a ton of great blogs that look under the hood of #nodejs code. Check them out here https://t.co/kDim27DNRl',
truncated: false,
entities:
{ hashtags: [Array],
symbols: [],
user_mentions: [Array],
urls: [Array] },
source: '<a href="http://sproutsocial.com" rel="nofollow">Sprout Social</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
{ id: 91985735,
id_str: '91985735',
name: 'Node.js',
screen_name: 'nodejs',
location: 'Earth',
description: 'The Node.js JavaScript Runtime',
url: 'https://t.co/X32n3a0B1h',
entities: [Object],
protected: false,
followers_count: 515428,
friends_count: 718,
listed_count: 6714,
created_at: 'Mon Nov 23 10:57:50 +0000 2009',
favourites_count: 1569,
utc_offset: -25200,
time_zone: 'Pacific Time (US & Canada)',
geo_enabled: true,
verified: true,
statuses_count: 5384,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/702185727262482432/n1JRsFeB_normal.png',
profile_banner_url: 'https://pbs.twimg.com/profile_banners/91985735/1513020552',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
jessieramirez (master *) liri-node-app $ node liri.js my-tweets
[ { created_at: 'Tue Jun 03 05:36:15 +0000 2014',
id: 473699662914789400,
id_str: '473699662914789376',
text: 'I\'m taking the 5-5-5 Challenge, are you? http://t.co/FJBvStctz4 via @sharethis',
truncated: false,
entities:
{ hashtags: [],
symbols: [],
user_mentions: [Array],
urls: [Array] },
source: '<a href="https://dev.twitter.com/docs/tfw" rel="nofollow">Twitter for Websites</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
{ id: 24412888,
id_str: '24412888',
name: 'Jeff Bongard',
screen_name: 'JBongo',
location: '',
description: '',
url: null,
entities: [Object],
protected: false,
followers_count: 3,
friends_count: 0,
listed_count: 0,
created_at: 'Sat Mar 14 19:04:41 +0000 2009',
favourites_count: 2,
utc_offset: null,
time_zone: null,
geo_enabled: false,
verified: false,
statuses_count: 4,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/571520062662524928/B9Ao9TlI_normal.jpeg',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/571520062662524928/B9Ao9TlI_normal.jpeg',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 0,
favorite_count: 0,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' },
{ created_at: 'Sun Jun 01 20:15:47 +0000 2014',
id: 473196228390690800,
id_str: '473196228390690816',
text: 'RT @HiddenBrain: CC @TheRealJerryK RT @halfrat: The chapter in @HiddenBrain about herd mentality in crisis is fascinating and so so scary.',
truncated: false,
entities: { hashtags: [], symbols: [], user_mentions: [Array], urls: [] },
source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
{ id: 24412888,
id_str: '24412888',
name: 'Jeff Bongard',
screen_name: 'JBongo',
location: '',
description: '',
url: null,
entities: [Object],
protected: false,
followers_count: 3,
friends_count: 0,
listed_count: 0,
created_at: 'Sat Mar 14 19:04:41 +0000 2009',
favourites_count: 2,
utc_offset: null,
time_zone: null,
geo_enabled: false,
verified: false,
statuses_count: 4,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/571520062662524928/B9Ao9TlI_normal.jpeg',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/571520062662524928/B9Ao9TlI_normal.jpeg',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
retweeted_status:
{ created_at: 'Sun Jun 01 16:20:15 +0000 2014',
id: 473136957858807800,
id_str: '473136957858807808',
text: 'CC @TheRealJerryK RT @halfrat: The chapter in @HiddenBrain about herd mentality in crisis is fascinating and soso scary.',
truncated: false,
entities: [Object],
source: '<a href="http://www.hootsuite.com" rel="nofollow">Hootsuite</a>',
in_reply_to_status_id: 472899976171757600,
in_reply_to_status_id_str: '472899976171757568',
in_reply_to_user_id: 127560626,
in_reply_to_user_id_str: '127560626',
in_reply_to_screen_name: 'halfrat',
user: [Object],
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 5,
favorite_count: 3,
favorited: false,
retweeted: false,
lang: 'en' },
is_quote_status: false,
retweet_count: 5,
favorite_count: 0,
favorited: false,
retweeted: false,
lang: 'en' },
{ created_at: 'Wed Sep 25 19:49:08 +0000 2013',
id: 382954944015261700,
id_str: '382954944015261696',
text: '@sdmcbee @JeffVanderstelt Missional Communities; born of the heart, spirit-driven, spirit-lead, mission that endures.',
truncated: false,
entities: { hashtags: [], symbols: [], user_mentions: [Array], urls: [] },
source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
in_reply_to_status_id: 382935593140776960,
in_reply_to_status_id_str: '382935593140776960',
in_reply_to_user_id: 16442809,
in_reply_to_user_id_str: '16442809',
in_reply_to_screen_name: 'sdmcbee',
user:
{ id: 24412888,
id_str: '24412888',
name: 'Jeff Bongard',
screen_name: 'JBongo',
location: '',
description: '',
url: null,
entities: [Object],
protected: false,
followers_count: 3,
friends_count: 0,
listed_count: 0,
created_at: 'Sat Mar 14 19:04:41 +0000 2009',
favourites_count: 2,
utc_offset: null,
time_zone: null,
geo_enabled: false,
verified: false,
statuses_count: 4,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/571520062662524928/B9Ao9TlI_normal.jpeg',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/571520062662524928/B9Ao9TlI_normal.jpeg',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 0,
favorite_count: 0,
favorited: false,
retweeted: false,
lang: 'en' },
{ created_at: 'Thu Sep 19 01:04:17 +0000 2013',
id: 380497537922105340,
id_str: '380497537922105344',
text: 'Free Guide: What Everybody Ought To Know About Effective Evangelism | Verge Network http://t.co/tAtJEUm9iy',
truncated: false,
entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Array] },
source: '<a href="https://dev.twitter.com/docs/tfw" rel="nofollow">Twitter for Websites</a>',
in_reply_to_status_id: null,
in_reply_to_status_id_str: null,
in_reply_to_user_id: null,
in_reply_to_user_id_str: null,
in_reply_to_screen_name: null,
user:
{ id: 24412888,
id_str: '24412888',
name: 'Jeff Bongard',
screen_name: 'JBongo',
location: '',
description: '',
url: null,
entities: [Object],
protected: false,
followers_count: 3,
friends_count: 0,
listed_count: 0,
created_at: 'Sat Mar 14 19:04:41 +0000 2009',
favourites_count: 2,
utc_offset: null,
time_zone: null,
geo_enabled: false,
verified: false,
statuses_count: 4,
lang: 'en',
contributors_enabled: false,
is_translator: false,
is_translation_enabled: false,
profile_background_color: 'C0DEED',
profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
profile_background_tile: false,
profile_image_url: 'http://pbs.twimg.com/profile_images/571520062662524928/B9Ao9TlI_normal.jpeg',
profile_image_url_https: 'https://pbs.twimg.com/profile_images/571520062662524928/B9Ao9TlI_normal.jpeg',
profile_link_color: '1DA1F2',
profile_sidebar_border_color: 'C0DEED',
profile_sidebar_fill_color: 'DDEEF6',
profile_text_color: '333333',
profile_use_background_image: true,
has_extended_profile: false,
default_profile: true,
default_profile_image: false,
following: false,
follow_request_sent: false,
notifications: false,
translator_type: 'none' },
geo: null,
coordinates: null,
place: null,
contributors: null,
is_quote_status: false,
retweet_count: 0,
favorite_count: 0,
favorited: false,
retweeted: false,
possibly_sensitive: false,
lang: 'en' } ]